"""ADD UserFile table

Revision ID: c4fb137324d6
Revises: e6cd10a955d5
Create Date: 2023-05-13 21:49:21.242729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c4fb137324d6'
down_revision = 'e6cd10a955d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_file',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_downloadable', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_file_id'), 'user_file', ['id'], unique=True)
    op.create_index(op.f('ix_user_file_user_id'), 'user_file', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_file_user_id'), table_name='user_file')
    op.drop_index(op.f('ix_user_file_id'), table_name='user_file')
    op.drop_table('user_file')
    # ### end Alembic commands ###
