"""add short url tables

Revision ID: 971ffa478fe6
Revises: 
Create Date: 2023-04-30 22:47:38.032929

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '971ffa478fe6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('short_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_id'), 'short_url', ['id'], unique=True)
    op.create_index(op.f('ix_short_url_short_url'), 'short_url', ['short_url'], unique=True)
    op.create_table('short_url_log',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('short_url_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['short_url_id'], ['short_url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_url_log_id'), 'short_url_log', ['id'], unique=True)
    op.create_index(op.f('ix_short_url_log_short_url_id'), 'short_url_log', ['short_url_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_url_log_short_url_id'), table_name='short_url_log')
    op.drop_index(op.f('ix_short_url_log_id'), table_name='short_url_log')
    op.drop_table('short_url_log')
    op.drop_index(op.f('ix_short_url_short_url'), table_name='short_url')
    op.drop_index(op.f('ix_short_url_id'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
