app:
  project_name: async-python-sprint-5
  description: sprint 5 in Async Python Course in Yandex Praktikum
  version: 0.1.0
  api_doc_prefix: /api/v1
  host: 0.0.0.0
  port: 8000
  debug: true
  jwt_secret: "secret"
  jwt_lifetime: 3600

postgres:
  host: test_sprint_5_postgres_db
  port: 5432
  dbname: test
  user: test
  password: test

minio:
  host: minio
  port: 9000
  access_key: test
  secret_key: test
